### ISSUE TITLE
Salesforce Closed

### ISSUE THREAD

**Issue by sumanyumuku98** [bsovs/Fall2023-Internships#67]

**Comment by jaygupt** [comment]
That position is closed. Maybe we can replace it with this co-op position? https://salesforce.wd1.myworkdayjobs.com/en-US/External_Career_Site/job/Massachusetts---Burlington/Fall-Co-op---Software-Engineer--Full-stack---B2C-Commerce-Cloud_JR151275-1?source=LinkedIn_Jobs
